[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/remoteEntry.js"
  [headers.values]
  Cache-Control = "public, max-age=300, must-revalidate"
